fix join str_len
FalkorDB/FalkorDB pull request #48
Opened 2023-09-07 12:56 UTC by gkorland

2023-09-08 10:01 UTC, swilly22 requested changes

2023-09-08 10:01 UTC, swilly22 commented on src/arithmetic/string_funcs/string_funcs.c
>  	uint str_len = delimeter_len * (count - 1);
I believe the same overflow can happen where the delimiter is large and the number of elements in the array is significant. e.g. large delimiter * larger number of strings

2023-09-11 18:15 UTC, swilly22 requested changes

2023-09-11 18:15 UTC, swilly22 commented on src/arithmetic/string_funcs/string_funcs.c
> +		cur_len += val_len + delimeter_len;
I'm not sure this solution is right,
If both `str_len` and `cur_len` had overflowed, the following condition would pass and we will be overflowing the `res` buffer.

2023-09-12 13:38 UTC, gkorland commented on src/arithmetic/string_funcs/string_funcs.c
> +		cur_len += val_len + delimeter_len;
@swilly22 please recheck

2023-09-20 10:21 UTC, closed without merging