Decode multi edge
FalkorDB/FalkorDB pull request #826
Opened 2024-11-12 10:04 UTC by swilly22

fixes #825

2024-11-13 08:21 UTC, AviAvni requested changes

2024-11-13 08:21 UTC, AviAvni commented on src/graph/tensor/tensor.c
>  void Tensor_SetElements
what is the diff between Tensor_SetEdges and this function?

2024-11-13 08:21 UTC, AviAvni commented on src/serializers/decoders/current/v16/decode_graph_entities.c
> +static SIValue _RdbLoadVector
it look like we don't test loading vector from rdb

2024-11-13 08:21 UTC, AviAvni commented on src/serializers/decoders/current/v16/decode_graph_entities.c
> +		max_id = MAX(max_id, MAX(e.src_id, e.dest_id));
what we do with this max_id?

2024-11-13 08:21 UTC, AviAvni commented on src/serializers/decoders/prev/v10/decode_graph_entities.c
> +					dests, ids, idx, max_node_id, false);
take a look at all the uncovered lines in all decoders version

2024-11-13 14:01 UTC, swilly22 commented on tests/flow/test_prev_rdb_decode.py
> +    def _test_v9_decode(self):
👍

2024-11-13 14:02 UTC, swilly22 commented on src/serializers/decoders/current/v16/decode_graph_schema.c
> +	size_t *M, 		         // index field option M
👍

2024-11-13 14:03 UTC, swilly22 commented on src/serializers/graph_extensions.c
> +			//ASSERT(info == GrB_NO_VALUE);
👍

2024-11-13 14:04 UTC, swilly22 commented on src/serializers/decoders/current/v16/decode_graph_entities.c
> +		max_id = MAX(max_id, MAX(e.src_id, e.dest_id));
Removed, I don't believe it is needed.

2024-11-14 08:05 UTC, AviAvni requested changes

2024-11-14 08:19 UTC, swilly22 commented on src/serializers/decoders/current/v16/decode_graph_entities.c
> +		for(uint64_t i = 0; i < nodeLabelCount; i ++){
👍

2024-11-20 09:50 UTC, merged